export enum SharedEvents {
  CREATE_DOCTOR = 'create.doctor',
  DELETE_USER = 'delete.user',
  STORE_IDENTIFICATION = 'store.identification',
  CREATE_SMART_ACCOUNT = 'create.smart.account',
  UPDATE_USER_LOGIN = 'update.user.login',
  ADD_PATIENT_TO_CONTRACT = 'add.patient.to.contract',
  ADD_DOCTOR_TO_CONTRACT = 'add.doctor.to.contract',
  PATIENT_REGISTRATION = 'patient.registration',
  DOCTOR_REGISTRATION = 'doctor.registration',
  APPROVE_RECORD_ACCESS = 'approve.record.access',
  APPROVE_WRITE_ACCESS = 'approve.write.access',
  ADD_MEDICAL_RECORD_TO_CONTRACT = 'add.medical.record.to.contract',
  DELETE_APPROVAL = 'delete.approval',
  MINT_HEALTH_TOKEN = 'mint.health.token',
  BATCH_MINT_HEALTH_TOKEN = 'batch.mint.health.token',
  TASK_COMPLETED = 'task.completed',
  SEND_OTP = 'send.otp',
}
