name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #   - name: Copy env
    #     run: |
    #       echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set Image Tag
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
     
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/allofhealthapi:${{ env.IMAGE_TAG }} .
      
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/allofhealthapi:${{ env.IMAGE_TAG }}

  deploy_to_digitalocean:
    name: Deploy on DigitalOcean
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    #   - name: Set up AWS CLI
    #     uses: aws-actions/configure-aws-credentials@v2
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: eu-north-1

      - name: Set Image Version
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DO_SSH_KEY}}
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/allofhealthapi:${{ env.IMAGE_TAG }}
            docker stop allofhealthapi || true
            docker rm allofhealthapi || true
            docker run -d -p 3003:3001 --name allofhealthapi ${{ secrets.DOCKERHUB_USERNAME }}/allofhealthapi:${{ env.IMAGE_TAG }}